### PR TITLE
Add support to talk directly to a PM.

### PR DESCRIPTION
**Pull request by ixs**
Only minor changes needed, effectively do not break on missing fields.

### CODE REVIEW

**Comment by knorrie** [comment]
Hi, your changes fix the code until there are no explosions any more. This is one way to do it. However, I took a bit different approach, since I didn't like a bunch of things in the code that I wrote 6 years ago.

It's commits "Rewrite all the structures stuff" and "Document difference in Outlet fields for ACS vs PM" on top of the develop branch.

All the mapping stuff and also the class level variables (ew) are gone now. The code is more generic, and it doesn't care about what kind of thing you connect to any more.

Besides that, I did a lot more code cleanups.

**Comment by ixs** [comment]
Oh wow. I see. Lots of commits.

The code looks much nicer. I have a (so far) private branch that adds the ability to somewhat configure outlets, e.g. naming, limits and timers. The changes should make things easier as I do not need to keep an extra mapping in structure.py around.

Let me see how I would best adapt this to the develop branch.

**Comment by knorrie** [comment]
Ooh, yes, renaming outlets would be nice.

If you can confirm that you can also connect directly to a PM and on/off outlets etc, then we can close this one. Then I'll merge to master, tag v2 and then we can continue from there.

Thanks.

**Comment by ixs** [comment]
Tested the develop branch, code looks good:

```
pmCommand# status
/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

  Outlet      Name             Status      Bank  Current (A)  Power (W)
  ==========  ===============  ==========  ====  ===========  =========
  Rechts[1]   hp2848_1         ON          N/A   0.0          0.0
  Rechts[2]   acs32_1          ON(locked)  N/A   0.0          0.0
  Rechts[3]   bb1_1            ON          N/A   0.0          0.0
  Rechts[4]   bb2_1            ON          N/A   0.2          37.0
  Rechts[5]   carbon_1         ON          N/A   0.0          0.0
  Rechts[6]   22-c9-dcP0_1_6   ON          N/A   0.0          0.0
  Rechts[7]   22-c9-dcP0_1_7   ON          N/A   0.0          0.0
  Rechts[8]   22-c9-dcP0_1_8   ON          N/A   0.6          104.0
  Rechts[9]   horscht_1        ON          N/A   0.0          0.0
  Rechts[10]  sysiphus_1       ON          N/A   0.2          42.0
  Rechts[11]  22-c9-dcP0_1_11  ON          N/A   0.6          134.0
  Rechts[12]  virt1_1          ON          N/A   0.3          77.0
  Rechts[13]  virt2_1          ON          N/A   0.5          110.0
  Rechts[14]  virt3_1          ON          N/A   0.3          78.0
  Rechts[15]  switch-mgmt_1    ON(locked)  N/A   0.0          0.0
  Rechts[16]  22-c9-dcP0_1_16  ON          N/A   0.0          0.0
  Rechts[17]  filer1_1         ON          N/A   0.6          133.0
  Rechts[18]  filer2_1         ON          N/A   0.5          103.0
  Rechts[19]  stk_1            ON          N/A   0.4          80.0
  Rechts[20]  22-c9-dcP0_1_20  ON          N/A   0.0          0.0
```
Powercycle works too.

We should just silence the urllib3 warning. urllib3.disable_warnings() did not work for me though, need to have a closer look if I used it in the right place.

**Comment by knorrie** [comment]
Ok, can you try latest commit? It should silence all of that.

**Comment by knorrie** [comment]
~Oh, it doesn't. Grmbl, duh.~  Now it should, with requests.packages.urllib3.disable_warnings(). I don't see them any more.

**Comment by ixs** [comment]
Looks good.

**Pull request closed without merging**
